/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bagdhpqzwxelbgbvubfr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZ2RocHF6d3hlbGJnYnZ1YmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MDg5NzMsImV4cCI6MjA3NjI4NDk3M30.FwD-YT3OxpqKCK9T2s9-HtSuuLZRxGulnSui2JIdmd8"