
export const verifiedPortfolioProjects = [
  {
    title: "Palatial Petals",
    excerpt: "Luxury Floral Studio Brand & E-Commerce",
    category: "Brand Strategy",
    project_type: "Brand Refresh, E-Commerce & Content Systems",
    completion_date: "2024-04-10",
    client_name: "Palatial Petals",
    technologies: ["Figma", "Adobe Creative Suite", "Shopify", "Instagram API", "Zapier", "Airtable"],
    description: "Brand refresh for luxury floral studio including refined identity centered on elegance, romance, and quiet luxury. Designed custom e-commerce experience with modular product sections for gifting, events, and collaborations. Established poetic tone of voice with moodboard-driven content system blending editorial shots with lifestyle storytelling. Created automated workflows for order intake, delivery coordination, and content calendars.",
    results: "• Premium positioning as luxury floral destination\n• Automated order processing workflows deployed\n• Reusable content templates for brand consistency\n• Seamless mobile-optimized checkout experience",
    published: true,
    featured: true,
    slug: "palatial-petals"
  },
  {
    title: "IBÁ Mezcal",
    excerpt: "Premium Artisanal Spirits Social Strategy",
    category: "Social Media Management",
    project_type: "Q3 2025 Social Media Strategy",
    completion_date: "2025-09-30",
    client_name: "IBÁ Mezcal",
    technologies: ["Meta Business Suite", "Later", "Canva", "Adobe Lightroom", "Google Analytics"],
    description: "Q3 2025 social media strategy for premium artisanal mezcal brand with weekly content calendars, professional photography, cocktail recipe content, and monthly analytics reports. Developed content pillars focused on heritage storytelling and lifestyle integration.",
    results: "• 22% follower growth target (Q3 2025)\n• $3,500/month active retainer maintained\n• Weekly content calendar execution\n• Monthly analytics reports delivered",
    published: true,
    featured: false,
    slug: "iba-mezcal"
  },
  {
    title: "Signature Cocktail Co.",
    excerpt: "RTD Beverage Social Media Management",
    category: "Social Media Management",
    project_type: "Content Management & Performance Analytics",
    completion_date: "2025-08-15",
    client_name: "Signature Cocktail Co.",
    technologies: ["Meta Business Suite", "Hootsuite", "Instagram Insights", "Canva", "Adobe Premiere Pro"],
    description: "Daily social media content management for premium ready-to-drink cocktail brand including bartender Reel production, performance reports with engagement analytics, and brand voice guidelines development.",
    results: "• Daily content management schedule established\n• Bartender Reels driving product education\n• Performance reports with actionable insights\n• Brand voice consistency across platforms",
    published: true,
    featured: false,
    slug: "signature-cocktail-co"
  },
  {
    title: "EJAI",
    excerpt: "Wellness & Biohacking Social Strategy",
    category: "Social Media Strategy",
    project_type: "Multi-Platform Content Strategy",
    completion_date: "2025-10-14",
    client_name: "EJAI",
    technologies: ["Instagram", "TikTok", "LinkedIn", "Notion", "Figma", "Canva"],
    description: "Multi-platform social media strategy for wellness and biohacking brand with educational content series across Instagram, TikTok, and LinkedIn. Master Doc created August 15, 2025 with visual identity refinement and messaging frameworks.",
    results: "• 3-platform strategy deployed (Instagram/TikTok/LinkedIn)\n• Master Doc framework for consistency\n• Educational content series launched\n• Visual identity refinement completed",
    published: true,
    featured: false,
    slug: "ejai"
  },
  {
    title: "AveLux",
    excerpt: "Luxury Wellness Sanctuary Brand",
    category: "Content Creation",
    project_type: "AI-Generated Monthly Content & Brand Strategy",
    completion_date: null,
    client_name: "AveLux (TheAveLux)",
    technologies: ["Midjourney", "DALL-E 3", "Adobe Photoshop", "Figma"],
    description: "Monthly AI-generated luxury content (2-3 premium posts) at $150/month positioning sanctuary for transformation. Developed brand narrative around FOCUS values and DARE Method with 30-day content calendar blending soulful insights and emotional depth.",
    results: "• $150/month retainer ongoing\n• 2-3 AI-generated posts monthly\n• High-EQ clientele targeted successfully\n• \"Not Exclusive. Just Intentional\" positioning established",
    published: true,
    featured: false,
    slug: "avelux"
  },
  {
    title: "Vanbike",
    excerpt: "German Market Mobility Brand",
    category: "Social Media Management",
    project_type: "Localized Content & Pinterest Automation",
    completion_date: "2025-10-23",
    client_name: "Vanbike",
    technologies: ["Pinterest Business", "Tailwind", "Instagram", "Facebook", "Canva", "Deepl"],
    description: "German-language social media content and Pinterest automation for mobility brand in DACH region. Developed campaigns with culturally adapted messaging and localized hashtag strategies. Created cohesive brand identity with bold, modern logo and full visual system.",
    results: "• 47% increase in bookings post-launch\n• Pinterest automation driving consistent traffic\n• German-language content for DACH market\n• Social engagement steadily increased",
    published: true,
    featured: false,
    slug: "vanbike"
  },
  {
    title: "SCP",
    excerpt: "Sustainable CRE Lending Platform",
    category: "Web Development",
    project_type: "Website Development & Brand Collateral",
    completion_date: "2025-07-29",
    client_name: "SCP / acenosX",
    technologies: ["Webflow", "Figma", "Adobe Creative Suite", "Google Analytics", "Calendly", "HubSpot"],
    description: "Complete website development for sustainable CRE lending platform showcasing $60B+ experience with flexible mortgages funding acquisitions and 100% sustainability retrofits. Created brand collateral suite with ROI-focused tear sheets, business cards, and templates.",
    results: "• 22% utility savings demonstrated\n• 11% insurance reduction proven\n• $3.1M valuation increase showcased\n• $60B+ combined experience highlighted",
    live_url: "https://scpcre.com",
    published: true,
    featured: true,
    slug: "scp-cre"
  },
  {
    title: "Searchfund",
    excerpt: "Investment Partnership Website",
    category: "Web Development",
    project_type: "Website Finalization & Brand Kit",
    completion_date: "2025-07-29",
    client_name: "Searchfund",
    technologies: ["Web Development Platform", "Google Drive"],
    description: "Website finalization including partnership section with Akira logo integration, blog optimization (July 2025), and technical fixes. Brand kit compilation with transition to monthly retainer structure.",
    results: "• Website finalized with partnership logos\n• Blog optimized for July 2025 launch\n• Monthly retainer engagement transitioned\n• Brand kit delivered for consistency",
    published: true,
    featured: false,
    slug: "searchfund"
  },
  {
    title: "MAST Legal",
    excerpt: "Future-Focused Law Firm Platform",
    category: "Web Development",
    project_type: "Website Development & Service Positioning",
    completion_date: "2025-07-29",
    client_name: "MAST Legal",
    technologies: ["Web Development Platform", "Figma", "Adobe Creative Suite"],
    description: "Complete website for corporate law firm showcasing 2,500+ successful deals across Venture Capital, Corporate Transactions, and Product Launch Strategy. Designed mobile-optimized platform with international capabilities across 23+ countries.",
    results: "• 2,500+ cases prominently featured\n• 23+ countries coverage highlighted\n• Mobile-optimized user experience\n• Scalable client acquisition tool launched",
    live_url: "https://mast.legal",
    published: true,
    featured: true,
    slug: "mast-legal"
  },
  {
    title: "AI Insiders",
    excerpt: "AI Business Coaching Platform",
    category: "Brand Identity",
    project_type: "Logo Design & Visual System",
    completion_date: "2025-07-23",
    client_name: "AI Insiders",
    technologies: ["Adobe Creative Suite", "Figma"],
    description: "Logo design and brand identity through multiple iterations (June 17, 2025). Designed sleek logo, refined palette, and clean visual framework. Applied consistent branding across digital, print, and event materials.",
    results: "• Modern credible brand established\n• Community growth supported\n• Thought leadership positioning achieved\n• Partnership attraction increased",
    live_url: "https://goinsiders.ai",
    published: true,
    featured: true,
    slug: "ai-insiders"
  },
  {
    title: "Alexander Hotel",
    excerpt: "Luxury Oceanfront Event Marketing",
    category: "Event Design",
    project_type: "Wedding Proposals & Venue Marketing",
    completion_date: "2025-07-23",
    client_name: "Alexander Hotel",
    technologies: ["Adobe Creative Suite", "Figma"],
    description: "Comprehensive wedding proposal (completed July 23, 2025) with luxury-tier presentation for high-net-worth clients. Developed moodboards for The Orchid Room and magazine editorial content for travel media placement.",
    results: "• High-conversion wedding proposals created\n• The Orchid Room positioned as exclusive venue\n• Magazine-ready content for lifestyle media\n• \"Miami's ultimate waterfront retreat\" established",
    live_url: "https://alexanderhotel.com",
    published: true,
    featured: true,
    slug: "alexander-hotel"
  },
  {
    title: "WELDA Club",
    excerpt: "Global Wellness Movement Launch",
    category: "Complete Brand Launch",
    project_type: "Brand, Business Setup, Website & Events",
    completion_date: "2025-08-06",
    client_name: "WELDA Club",
    technologies: ["Wix", "Social Media Tools", "Event Management Systems"],
    description: "Complete brand launch including business infrastructure, website with event booking, multi-city coordination (Miami/NYC), and full brand system. Executed WELDA Yoga Event (July 26, 2025). Produced $10M+ expansion model for Bali, Berlin, Tulum, London.",
    results: "• 2 cities launched (Miami, NYC)\n• $10M+ expansion model investor-ready\n• Successful launch events executed\n• 4 additional cities planned (Bali, Berlin, Tulum, London)",
    live_url: "https://weldaclub.com",
    published: true,
    featured: true,
    slug: "welda-club"
  },
  {
    title: "Optodex",
    excerpt: "MedTech Innovation Marketing",
    category: "Content Strategy",
    project_type: "Newsletter Strategy & Launch Communications",
    completion_date: "2025-01-01",
    client_name: "Optodex",
    technologies: ["Email Design Tools", "Marketing Platforms"],
    description: "Newsletter strategy for world's first finger-free contact lens system with patented Y-Tip™ applicator. Created launch communications and product education content. Built dual-audience strategy for consumers and eye care professionals.",
    results: "• 15% launch discount campaign\n• Category-defining brand positioned\n• Dual-audience strategy (consumer + clinical)\n• Global distribution readiness achieved",
    live_url: "https://optodex.com",
    published: true,
    featured: false,
    slug: "optodex"
  },
  {
    title: "Rockhill Capital",
    excerpt: "Houston Private Equity Firm",
    category: "Web Development",
    project_type: "Website Development & Portfolio Showcase",
    completion_date: "2025-01-01",
    client_name: "Rockhill Capital",
    technologies: ["Web Development Platform", "Adobe Creative Suite"],
    description: "Complete website for Houston-based PE firm (founded 2007) with dedicated sections for Strategy, Portfolio, Team, News, Investor Portal. Built dynamic portfolio section showcasing 10 operating company investments with 17+ years track record.",
    results: "• 17+ years experience showcased\n• 10 operating companies highlighted\n• South & Southeast U.S. focus established\n• \"More Than Capital\" positioning strengthened",
    live_url: "https://rockhillcap.com",
    published: true,
    featured: true,
    slug: "rockhill-capital"
  },
  {
    title: "Parceros Capital",
    excerpt: "Legacy-Focused Acquisition Firm",
    category: "Web Development",
    project_type: "Complete Brand System & Website",
    completion_date: "2025-01-01",
    client_name: "Parceros Capital",
    technologies: ["Web Development Platform", "Adobe Creative Suite"],
    description: "Complete brand system including naming, visual identity (logo suite, palette, typography), comprehensive guidelines, and website optimized for clarity and trust-building. Monthly engagement protocols for brand upkeep and market positioning.",
    results: "• \"Operators not private equity\" differentiation\n• Premium partner positioning achieved\n• Monthly engagement protocols established\n• Legacy preservation mission communicated",
    live_url: "https://parceroscapital.com",
    published: true,
    featured: true,
    slug: "parceros-capital"
  },
  {
    title: "3Spoke Capital",
    excerpt: "Institutional VC Secondaries Positioning",
    category: "Brand Strategy",
    project_type: "Strategic Messaging & Competitive Analysis",
    completion_date: "2025-11-12",
    client_name: "3Spoke Capital",
    technologies: ["Strategic Analysis Tools", "Google Workspace"],
    description: "Strategic messaging framework for institutional-grade investment firm transitioning from $1-5M retail to $25-75M transactions with VCs, pension plans, corporate venture arms. Positioned against 31 active VC secondaries buyers.",
    results: "• $1-5M to $25-75M transaction tier shift\n• 31 competitors analyzed\n• Institutional messaging framework created\n• Target audience refined (VCs, pension plans, corporate)",
    published: true,
    featured: false,
    slug: "3spoke-capital"
  },
  {
    title: "Strategi Builder",
    excerpt: "Complete Brand Collateral Suite",
    category: "Brand Identity",
    project_type: "Logo, Stationery & Social Assets",
    completion_date: "2026-02-02",
    client_name: "Strategi Builder",
    technologies: ["Adobe Creative Suite", "Figma"],
    description: "Complete brand collateral including logo, business cards, letterhead, email signatures, LinkedIn header, social media assets. All deliverables organized in Google Drive (ID: 1nCuipRjHsYfiIm-EKF4mvvK3GdjxEZ3f).",
    results: "• 6+ brand collateral pieces delivered\n• February 2, 2026 completion\n• Organized Google Drive structure\n• All touchpoints consistent",
    published: true,
    featured: false,
    slug: "strategi-builder"
  },
  {
    title: "Bloom Talent",
    excerpt: "Talent Acquisition Platform Brand",
    category: "Brand Strategy",
    project_type: "Brand Identity & Positioning",
    completion_date: "2025-10-27",
    client_name: "Bloom Talent",
    technologies: ["Brand Strategy Tools", "Adobe Creative Suite"],
    description: "Brand development for talent acquisition platform with comprehensive strategy and visual identity. Dedicated project folder (ID: 1bSH-jkyHJ-iaxfq2z1KwAvWv9BTe8iXR) established October 27, 2025.",
    results: "• Brand strategy framework completed\n• Visual identity system developed\n• Talent marketplace positioning established\n• Digital platform foundation laid",
    published: true,
    featured: false,
    slug: "bloom-talent"
  },
  {
    title: "White Rock",
    excerpt: "Financial Firm Brand Modernization",
    category: "Brand Identity",
    project_type: "Logo Refresh & Corporate Identity",
    completion_date: "2024-07-15",
    client_name: "White Rock by Intuity Group",
    technologies: ["Adobe Creative Suite", "Figma"],
    description: "Complete brand refresh including logo redesign, visual framework (Teal, Dark Teal, Light Teal, Cream palette), business cards on premium uncoated stock, letterheads, digital templates. LinkedIn thought leadership strategy developed.",
    results: "• Complete brand guidelines delivered\n• LinkedIn connection rates increased\n• Premium paper stock collateral\n• Brand authority elevated in PE sector",
    published: true,
    featured: false,
    slug: "white-rock"
  },
  {
    title: "Whitestone & Co.",
    excerpt: "Mission-Driven Real Estate Investment",
    category: "Brand Strategy",
    project_type: "Website Enhancement & Investor Materials",
    completion_date: "2025-01-01",
    client_name: "Whitestone & Co.",
    technologies: ["Web Development Platform", "Adobe Creative Suite"],
    description: "Brand refresh for real estate firm serving low-income families, seniors, people with disabilities. Improved website structure, designed fund reports, bridge loan summaries, investor collateral reinforcing trust and transparency.",
    results: "• Clearer investor communication\n• Trust and transparency reinforced\n• Investment increase supported\n• Social mission + returns balanced",
    published: true,
    featured: false,
    slug: "whitestone-co"
  },
  {
    title: "Bon Bouquet",
    excerpt: "French Café Cultural Destination",
    category: "Complete Brand Launch",
    project_type: "Brand Identity, Website, Social & Interior",
    completion_date: "2024-01-01",
    client_name: "Bon Bouquet",
    technologies: ["Wix", "Instagram", "Social Media Management Tools", "Adobe Creative Suite"],
    description: "Complete launch for French-inspired Miami Beach café including brand identity (logo, palette, typography), merchandise, window decals, website. Managed social from zero with content calendar, influencer partnerships, original photography.",
    results: "• 0 to 2,500+ followers in 3 months\n• 4,000+ monthly website visitors\n• Cultural destination status achieved\n• Photographed and shared organically",
    published: true,
    featured: false,
    slug: "bon-bouquet"
  },
  {
    title: "Loutfi Aesthetics",
    excerpt: "Medical Aesthetics Luxury Rebrand",
    category: "Social Media Management",
    project_type: "Social Media Transformation",
    completion_date: "2025-01-01",
    client_name: "Loutfi Aesthetics",
    technologies: ["Instagram", "Content Creation Tools", "Adobe Creative Suite"],
    description: "Social transformation for medical beauty clinic with polished luxury Instagram grid, before-and-after transformation formats, educational posts, influencer partnerships, and community engagement tactics.",
    results: "• Luxury-style Instagram grid established\n• Before/after credibility formats\n• Influencer partnerships built\n• Trust and following increased",
    published: true,
    featured: false,
    slug: "loutfi-aesthetics"
  },
  {
    title: "Kontaktsource",
    excerpt: "Professional Networking Platform Rebrand",
    category: "Brand Identity",
    project_type: "Complete Brand Refresh",
    completion_date: "2025-01-01",
    client_name: "Kontaktsource",
    technologies: ["Web Development Platform", "Adobe Creative Suite", "Figma", "LinkedIn"],
    description: "Complete refresh including modern logo, visual language, brand tone, contemporary palette and type system. Designed minimalist website with intuitive navigation and mobile responsiveness. Built branded decks, digital materials, social templates.",
    results: "• Immediate trust established\n• Credible player positioning\n• Stronger partnerships enabled\n• Scalable growth foundation",
    published: true,
    featured: false,
    slug: "kontaktsource"
  },
  {
    title: "EŪDAI",
    excerpt: "Ultra-Luxury Lifestyle Concierge",
    category: "Brand Identity",
    project_type: "UHNW Brand Development",
    completion_date: null,
    client_name: "EŪDAI",
    technologies: ["Adobe Creative Suite", "Web Development"],
    description: "Brand development for UHNW lifestyle management (real estate, art, concierge). Guided naming, developed identity rooted in luxury/well-being/discretion. Defined tone centered on personalized service and quiet excellence. Web and social in development.",
    results: "• High-trust brand foundation\n• UHNW positioning established\n• Miami luxury market entry\n• Web/social launch in development",
    published: true,
    featured: false,
    slug: "eudai"
  },
  {
    title: "AC's Trust",
    excerpt: "Right Walk PE Financial Trust",
    category: "Brand Identity",
    project_type: "Institutional Rebrand",
    completion_date: "2025-01-01",
    client_name: "AC's Trust / Right Walk",
    technologies: ["Adobe Creative Suite", "Presentation Design Tools"],
    description: "Complete rebuild for PE financial trust including PE ecosystem positioning, authoritative design system (logo, typography, palette, layout), investor-focused tone/narrative, investor decks, summaries, print materials.",
    results: "• Capital raising capability enhanced\n• Investment partnership foundation\n• Professional presence established\n• Institutional credibility achieved",
    published: true,
    featured: false,
    slug: "acs-trust"
  },
  {
    title: "Elevate Planners",
    excerpt: "Legacy-Focused RIA Firm",
    category: "Brand Identity",
    project_type: "Complete Brand & Digital Presence",
    completion_date: "2025-01-01",
    client_name: "Elevate Planners",
    technologies: ["Web Development Platform", "Adobe Creative Suite"],
    description: "Complete identity and digital presence for RIA firm. Developed sophisticated visual system, user-friendly responsive website, branded decks/brochures/stationery. Ongoing design and content support for campaigns and maintenance.",
    results: "• Client acquisition supported\n• Trust built through design\n• Growth foundation established\n• Consistent touchpoints maintained",
    published: true,
    featured: false,
    slug: "elevate-planners"
  },
  {
    title: "Holiday Inn Stuttgart",
    excerpt: "Holiday Season Digital Campaign",
    category: "Social Media Management",
    project_type: "Seasonal Content Strategy",
    completion_date: "2024-12-01",
    client_name: "Holiday Inn Stuttgart",
    technologies: ["Social Media Platforms", "Video Production", "Adobe Creative Suite"],
    description: "Festive strategy for Thanksgiving, Christmas, New Year offers. Built seasonal calendar with countdowns, themed posts, limited-time promotions. Designed photo/video assets showcasing décor, dining, ambiance. Produced optimized stories and reels.",
    results: "• Seasonal visibility increased\n• Consistent brand presence maintained\n• Engagement during competitive period boosted\n• Short-term bookings and long-term affinity",
    published: true,
    featured: false,
    slug: "holiday-inn-stuttgart"
  },
  {
    title: "Klarité Salon",
    excerpt: "At-Home Luxury Beauty Pioneer",
    category: "Complete Brand Launch",
    project_type: "Brand, Website & Business Setup",
    completion_date: "2024-01-01",
    client_name: "Klarité Salon",
    technologies: ["Web Development Platform", "Booking System", "Social Media Tools"],
    description: "Complete launch for at-home luxury beauty. Created name and identity, built mobile-optimized website with booking system, developed high-end social guidelines, supported pricing strategy and customer journey mapping.",
    results: "• At-home beauty category leadership\n• Miami high-end clientele targeted\n• Seamless booking experience\n• Standout visual identity",
    published: true,
    featured: false,
    slug: "klarite-salon"
  },
  {
    title: "Zen Botanica",
    excerpt: "Digital Herbal Wellness Platform",
    category: "E-Commerce & Brand Identity",
    project_type: "Brand Launch & E-Commerce Build",
    completion_date: "2024-01-01",
    client_name: "Zen Botanica / Vital Balance Acupuncture",
    technologies: ["E-Commerce Platform", "SEO Tools", "Booking System"],
    description: "Modern herbal platform launch as Vital Balance sub-brand. Nature-inspired brand system, user-friendly website with booking/purchase functionality, mobile-first design, foundational SEO, educational content, intuitive consultation/checkout paths.",
    results: "• 50% online engagement increase (3 months)\n• 35% consultations/sales lift (3 months)\n• Physical-digital bridge successful\n• Modern reach with natural wellness",
    published: true,
    featured: false,
    slug: "zen-botanica"
  },
  {
    title: "AARX Weight Loss",
    excerpt: "Science-Backed Weight Loss Clinic",
    category: "Content Strategy",
    project_type: "Brand & Educational Content",
    completion_date: "2025-01-01",
    client_name: "AARX Weight Loss",
    technologies: ["Social Media Platforms", "Content Design Tools"],
    description: "Brand development for clinical startup (Semaglutide, Zepatide, Ritruderide). Updated visuals balancing medical credibility with warmth. Content themes on education/trust/outcomes. Templates for carousels, FAQs, treatment overviews. Visual explainers simplifying science.",
    results: "• Clear, credible clinical brand\n• Trusted medical weight loss entry\n• Content system converting effectively\n• Growth in expanding health market",
    published: true,
    featured: false,
    slug: "aarx-weight-loss"
  }
];
